### ISSUE TITLE
 raise ValueError("bad input shape {0}".format(shape)) ValueError: bad input shape (28709, 7)

### ISSUE THREAD

**Issue by monajalal** [amineHorseman/facial-expression-recognition-svm#2]
Can you please suggest how to fix this?
```
[jalal@goku facial-expression-recognition-svm]$ python convert_fer2013_to_images_and_landmarks.py --landmarks=yes --hog=yes --jpg=no --onehot=yes
preparing
importing csv file
converting set: Training...
/scratch/sjn/anaconda/lib/python3.6/site-packages/skimage/feature/_hog.py:119: skimage_deprecation: Default value of `block_norm`==`L1` is deprecated and will be changed to `L2-Hys` in v0.15
  'be changed to `L2-Hys` in v0.15', skimage_deprecation)
converting set: PublicTest...
converting set: PrivateTest...
[jalal@goku facial-expression-recognition-svm]$ python train.py --train=yes
loading dataset Fer2013...
building model...
start training...
--
kernel: rbf
decision function: ovr
max epochs: 10000
--
Training samples: 28709
Validation samples: 3589
--
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    train()
  File "train.py", line 35, in train
    model.fit(data['X'], data['Y'])
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/sklearn/svm/base.py", line 149, in fit
    X, y = check_X_y(X, y, dtype=np.float64, order='C', accept_sparse='csr')
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py", line 547, in check_X_y
    y = column_or_1d(y, warn=True)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py", line 583, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape (28709, 7)
```

**Comment by monajalal** [comment]
solution to this is using one_hot=no
